name: Link Checker
on:
  schedule:
    - cron:  '0 0 * * 6'
jobs:
  Sort:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - name: Check Link
      run: npm install -D && node link-checker.js
