name: Awesome readme lint double link action
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master
    paths:
      - 'README_RAW.md'
jobs:
  build:
    name: awesome readme lint double link
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Scrum/awesome-readme-lint-double-link-action@v0.1.13
        with:
          entry: 'README_RAW.md'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
